import type {
  Category,
  Product,
  Supplier,
  DailyRevenue,
  Order,
  PurchaseOrder,
  StockAlert,
  PaymentMethod,
  Customer,
} from "./types";

export type {
  Category,
  Product,
  Supplier,
  DailyRevenue,
  Order,
  PurchaseOrder,
  StockAlert,
  PaymentMethod,
  Customer,
};

export const CATEGORIES: Category[] = [
  "Tất cả",
  "Ốp lưng",
  "Cáp",
  "Củ sạc",
  "Tai nghe",
  "Kính cường lực",
  "Pin dự phòng",
  "Khác",
];

const IMG_PLACEHOLDER =
  "https://placehold.co/400x400/e0e7ff/6366f1?text=Product";
const IMG_PLACEHOLDER_2 =
  "https://placehold.co/400x400/fef3c7/f59e0b?text=View2";
const IMG_PLACEHOLDER_3 =
  "https://placehold.co/400x400/d1fae5/10b981?text=View3";

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Ốp lưng Silicon iPhone 15 Pro Max",
    category: "Ốp lưng",
    sku: "CASE-IP15PM-001",
    barcode: "8901234567890",
    brand: "CaseMate",
    compatibleDevices: ["iPhone 15 Pro Max"],
    color: "Đen",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Ốp lưng Silicon iPhone 15 Pro Max - Mặt trước" },
      { url: IMG_PLACEHOLDER_2, alt: "Ốp lưng Silicon iPhone 15 Pro Max - Mặt sau" },
    ],
    dateImport: "2026-07-15",
    priceIn: 25000,
    priceOut: 49000,
    stockQty: 120,
    minStock: 20,
    status: "active",
    vat: true,
    note: "Silicone mềm, chống sốc",
  },
  {
    id: "p2",
    name: "Ốp lưng Leather Samsung S24 Ultra",
    category: "Ốp lưng",
    sku: "CASE-S24U-002",
    barcode: "8901234567891",
    brand: "Nillkin",
    compatibleDevices: ["Samsung Galaxy S24 Ultra"],
    color: "Nâu",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Ốp lưng Leather Samsung S24 Ultra" },
    ],
    dateImport: "2026-07-18",
    priceIn: 45000,
    priceOut: 89000,
    stockQty: 8,
    minStock: 15,
    status: "active",
    vat: true,
    note: "Da thật cao cấp",
  },
  {
    id: "p3",
    name: "Ốp lưng Trong suốt Xiaomi 14",
    category: "Ốp lưng",
    sku: "CASE-X14-003",
    barcode: "8901234567892",
    brand: "Baseus",
    compatibleDevices: ["Xiaomi 14"],
    color: "Trong suốt",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Ốp lưng Trong suốt Xiaomi 14" },
    ],
    dateImport: "2026-07-20",
    priceIn: 15000,
    priceOut: 35000,
    stockQty: 200,
    minStock: 30,
    status: "active",
    vat: false,
  },
  {
    id: "p4",
    name: "Cáp USB-C 2m tốc độ cao",
    category: "Cáp",
    sku: "CBL-USBC-001",
    barcode: "8901234567893",
    brand: "Anker",
    compatibleDevices: ["Universal USB-C"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Cáp USB-C 2m" },
      { url: IMG_PLACEHOLDER_3, alt: "Cáp USB-C 2m - Cận cảnh" },
    ],
    dateImport: "2026-07-10",
    priceIn: 18000,
    priceOut: 45000,
    stockQty: 55,
    minStock: 10,
    status: "active",
    vat: true,
  },
  {
    id: "p5",
    name: "Cáp Lightning 1m chính hãng",
    category: "Cáp",
    sku: "CBL-LIGHT-001",
    barcode: "8901234567894",
    brand: "Apple",
    compatibleDevices: ["iPhone 13/14/15"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Cáp Lightning 1m" },
    ],
    dateImport: "2026-07-12",
    priceIn: 35000,
    priceOut: 79000,
    stockQty: 3,
    minStock: 10,
    status: "active",
    vat: true,
    note: "Hàng chính hãng Apple",
  },
  {
    id: "p6",
    name: "Cáp Micro-USB 1.5m",
    category: "Cáp",
    sku: "CBL-MICRO-001",
    barcode: "8901234567895",
    brand: "Baseus",
    compatibleDevices: ["Android cũ"],
    color: "Đen",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Cáp Micro-USB 1.5m" },
    ],
    dateImport: "2026-07-14",
    priceIn: 8000,
    priceOut: 22000,
    stockQty: 180,
    minStock: 20,
    status: "active",
    vat: false,
  },
  {
    id: "p7",
    name: "Củ sạc nhanh 65W GaN",
    category: "Củ sạc",
    sku: "CHG-65W-001",
    barcode: "8901234567896",
    brand: "Anker",
    compatibleDevices: ["Universal PD"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Củ sạc 65W GaN" },
      { url: IMG_PLACEHOLDER_2, alt: "Củ sạc 65W GaN - Cận cảnh" },
    ],
    dateImport: "2026-07-08",
    priceIn: 180000,
    priceOut: 350000,
    stockQty: 40,
    minStock: 10,
    status: "active",
    vat: true,
  },
  {
    id: "p8",
    name: "Củ sạc dự phòng 10000mAh",
    category: "Củ sạc",
    sku: "CHG-PB10K-001",
    barcode: "8901234567897",
    brand: "Xiaomi",
    compatibleDevices: ["Universal"],
    color: "Đen",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Pin dự phòng 10000mAh" },
    ],
    dateImport: "2026-07-09",
    priceIn: 120000,
    priceOut: 249000,
    stockQty: 25,
    minStock: 10,
    status: "active",
    vat: true,
  },
  {
    id: "p9",
    name: "Củ sạc nhanh 30W USB-C",
    category: "Củ sạc",
    sku: "CHG-30W-001",
    barcode: "8901234567898",
    brand: "Baseus",
    compatibleDevices: ["Universal PD"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Củ sạc 30W USB-C" },
    ],
    dateImport: "2026-07-11",
    priceIn: 95000,
    priceOut: 189000,
    stockQty: 60,
    minStock: 15,
    status: "active",
    vat: true,
  },
  {
    id: "p10",
    name: "Tai nghe Bluetooth True Wireless TWS",
    category: "Tai nghe",
    sku: "EAR-TWS-001",
    barcode: "8901234567899",
    brand: "Baseus",
    compatibleDevices: ["Universal Bluetooth"],
    color: "Đen",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Tai nghe TWS" },
      { url: IMG_PLACEHOLDER_2, alt: "Tai nghe TWS - Hộp" },
    ],
    dateImport: "2026-07-22",
    priceIn: 85000,
    priceOut: 179000,
    stockQty: 35,
    minStock: 10,
    status: "active",
    vat: true,
  },
  {
    id: "p11",
    name: "Tai nghe Bluetooth cao cấp Sony WF-C700N",
    category: "Tai nghe",
    sku: "EAR-SONY-001",
    barcode: "8901234567900",
    brand: "Sony",
    compatibleDevices: ["Universal Bluetooth"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Tai nghe Sony WF-C700N" },
    ],
    dateImport: "2026-07-25",
    priceIn: 450000,
    priceOut: 899000,
    stockQty: 5,
    minStock: 5,
    status: "active",
    vat: true,
    note: "Hàng nhập khẩu chính hãng",
  },
  {
    id: "p12",
    name: "Tai nghe có dây Lightning Apple",
    category: "Tai nghe",
    sku: "EAR-LIGHT-001",
    barcode: "8901234567901",
    brand: "Apple",
    compatibleDevices: ["iPhone 15 trở lên"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Tai nghe có dây Lightning" },
    ],
    dateImport: "2026-07-26",
    priceIn: 300000,
    priceOut: 599000,
    stockQty: 18,
    minStock: 5,
    status: "active",
    vat: true,
  },
  {
    id: "p13",
    name: "Kính cường lực Samsung S24 Ultra 2 lớp",
    category: "Kính cường lực",
    sku: "GLASS-S24U-001",
    barcode: "8901234567902",
    brand: "ZAGG",
    compatibleDevices: ["Samsung Galaxy S24 Ultra"],
    color: "Trong suốt",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Kính cường lực Samsung S24 Ultra" },
    ],
    dateImport: "2026-07-16",
    priceIn: 35000,
    priceOut: 69000,
    stockQty: 90,
    minStock: 15,
    status: "active",
    vat: false,
  },
  {
    id: "p14",
    name: "Kính cường lực iPhone 15 Pro Max",
    category: "Kính cường lực",
    sku: "GLASS-IP15PM-001",
    barcode: "8901234567903",
    brand: "Spigen",
    compatibleDevices: ["iPhone 15 Pro Max"],
    color: "Trong suốt",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Kính cường lực iPhone 15 Pro Max" },
    ],
    dateImport: "2026-07-17",
    priceIn: 28000,
    priceOut: 55000,
    stockQty: 2,
    minStock: 10,
    status: "active",
    vat: false,
  },
  {
    id: "p15",
    name: "Kính cường lực Xiaomi 14 Pro",
    category: "Kính cường lực",
    sku: "GLASS-X14P-001",
    barcode: "8901234567904",
    brand: "Baseus",
    compatibleDevices: ["Xiaomi 14 Pro"],
    color: "Trong suốt",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Kính cường lực Xiaomi 14 Pro" },
    ],
    dateImport: "2026-07-19",
    priceIn: 22000,
    priceOut: 45000,
    stockQty: 65,
    minStock: 10,
    status: "active",
    vat: false,
  },
  {
    id: "p16",
    name: "Pin dự phòng 20000mAh sạc nhanh",
    category: "Pin dự phòng",
    sku: "PB-20K-001",
    barcode: "8901234567905",
    brand: "Anker",
    compatibleDevices: ["Universal PD"],
    color: "Đen",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Pin dự phòng 20000mAh" },
      { url: IMG_PLACEHOLDER_3, alt: "Pin dự phòng - Cổng sạc" },
    ],
    dateImport: "2026-07-21",
    priceIn: 280000,
    priceOut: 549000,
    stockQty: 15,
    minStock: 8,
    status: "active",
    vat: true,
  },
  {
    id: "p17",
    name: "Pin dự phòng 10000mAh slim",
    category: "Pin dự phòng",
    sku: "PB-10K-002",
    barcode: "8901234567906",
    brand: "Xiaomi",
    compatibleDevices: ["Universal"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Pin dự phòng 10000mAh slim" },
    ],
    dateImport: "2026-07-23",
    priceIn: 95000,
    priceOut: 189000,
    stockQty: 0,
    minStock: 10,
    status: "discontinued",
    vat: true,
  },
  {
    id: "p18",
    name: "Ốp lưng MagSafe iPhone 16",
    category: "Ốp lưng",
    sku: "CASE-IP16-001",
    barcode: "8901234567907",
    brand: "Apple",
    compatibleDevices: ["iPhone 16"],
    color: "Đen",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Ốp lưng MagSafe iPhone 16" },
    ],
    dateImport: "2026-07-28",
    priceIn: 85000,
    priceOut: 169000,
    stockQty: 50,
    minStock: 10,
    status: "active",
    vat: true,
  },
  {
    id: "p19",
    name: "Cáp USB-C sang Lightning 2m",
    category: "Cáp",
    sku: "CBL-CTR-001",
    barcode: "8901234567908",
    brand: "Anker",
    compatibleDevices: ["iPhone 13/14/15/16"],
    color: "Trắng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Cáp USB-C sang Lightning" },
    ],
    dateImport: "2026-07-29",
    priceIn: 25000,
    priceOut: 59000,
    stockQty: 80,
    minStock: 15,
    status: "active",
    vat: true,
  },
  {
    id: "p20",
    name: "Củ sạc nhanh 45W GaN siêu nhỏ",
    category: "Củ sạc",
    sku: "CHG-45W-002",
    barcode: "8901234567909",
    brand: "Baseus",
    compatibleDevices: ["Universal PD"],
    color: "Hồng",
    images: [
      { url: IMG_PLACEHOLDER, alt: "Củ sạc 45W GaN" },
    ],
    dateImport: "2026-07-30",
    priceIn: 130000,
    priceOut: 269000,
    stockQty: 30,
    minStock: 10,
    status: "active",
    vat: true,
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: "s1",
    name: "Công ty TNHH CaseMate Việt Nam",
    phone: "028 3845 1234",
    note: "Nhà cung cấp ốp lưng chính hãng",
  },
  {
    id: "s2",
    name: "Anker Việt Nam",
    phone: "028 3856 5678",
    note: "Cáp, củ sạc, pin dự phòng",
  },
  {
    id: "s3",
    name: "Cửa hàng phụ kiện TPHCM",
    phone: "0908 123 456",
    note: "Kính cường lực, ốp lưng giá sỉ",
  },
  {
    id: "s4",
    name: "Sony Audio Việt Nam",
    phone: "028 3920 7890",
    note: "Tai nghe chính hãng Sony",
  },
  {
    id: "s5",
    name: "Xiaomi Official Store",
    phone: "028 3710 1111",
    note: "Sản phẩm Xiaomi chính hãng",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "Nguyễn Văn An",
    phone: "0908 123 456",
    note: "Khách quen, mua hàng thường xuyên",
    createdAt: "2026-06-15",
  },
  {
    id: "c2",
    name: "Trần Thị Bình",
    phone: "0912 345 678",
    note: "",
    createdAt: "2026-06-20",
  },
  {
    id: "c3",
    name: "Lê Minh Cường",
    phone: "0934 567 890",
    note: "Mua sỉ, cần báo giá riêng",
    createdAt: "2026-07-01",
  },
  {
    id: "c4",
    name: "Phạm Thị Diệu",
    phone: "0945 678 901",
    note: "",
    createdAt: "2026-07-10",
  },
  {
    id: "c5",
    name: "Hoàng Văn Eo",
    phone: "0956 789 012",
    note: "Khách doanh nghiệp",
    createdAt: "2026-07-22",
  },
];

export const mockDailyRevenue: DailyRevenue[] = [
  { date: "2026-07-27", revenue: 4200000, orders: 18 },
  { date: "2026-07-28", revenue: 5100000, orders: 22 },
  { date: "2026-07-29", revenue: 3800000, orders: 15 },
  { date: "2026-07-30", revenue: 6200000, orders: 28 },
  { date: "2026-07-31", revenue: 5500000, orders: 24 },
  { date: "2026-08-01", revenue: 4700000, orders: 20 },
  { date: "2026-08-02", revenue: 5900000, orders: 25 },
];

export const mockRecentOrders: Order[] = [
  {
    id: "ORD-001",
    time: "2026-08-02T14:32:00",
    items: [
      {
        productId: "p1",
        productName: "Ốp lưng Silicon iPhone 15 Pro Max",
        qty: 2,
        unitPrice: 49000,
        lineTotal: 98000,
      },
      {
        productId: "p4",
        productName: "Cáp USB-C 2m tốc độ cao",
        qty: 1,
        unitPrice: 45000,
        lineTotal: 45000,
      },
    ],
    total: 143000,
    actualTotal: 143000,
    paymentMethod: "cash",
    customerId: "c1",
  },
  {
    id: "ORD-002",
    time: "2026-08-02T13:15:00",
    items: [
      {
        productId: "p7",
        productName: "Củ sạc nhanh 65W GaN",
        qty: 1,
        unitPrice: 350000,
        lineTotal: 350000,
      },
    ],
    total: 350000,
    actualTotal: 350000,
    paymentMethod: "transfer",
    customerId: "c3",
  },
  {
    id: "ORD-003",
    time: "2026-08-02T11:48:00",
    items: [
      {
        productId: "p13",
        productName: "Kính cường lực Samsung S24 Ultra 2 lớp",
        qty: 3,
        unitPrice: 69000,
        lineTotal: 207000,
      },
      {
        productId: "p10",
        productName: "Tai nghe Bluetooth True Wireless TWS",
        qty: 1,
        unitPrice: 179000,
        lineTotal: 179000,
      },
    ],
    total: 386000,
    actualTotal: 386000,
    paymentMethod: "cash",
    customerId: "c2",
  },
  {
    id: "ORD-004",
    time: "2026-08-02T10:20:00",
    items: [
      {
        productId: "p2",
        productName: "Ốp lưng Leather Samsung S24 Ultra",
        qty: 1,
        unitPrice: 89000,
        lineTotal: 89000,
      },
      {
        productId: "p15",
        productName: "Kính cường lực Xiaomi 14 Pro",
        qty: 2,
        unitPrice: 45000,
        lineTotal: 90000,
      },
    ],
    total: 179000,
    actualTotal: 180000,
    paymentMethod: "both",
    customerId: "c4",
  },
  {
    id: "ORD-005",
    time: "2026-08-02T09:05:00",
    items: [
      {
        productId: "p18",
        productName: "Ốp lưng MagSafe iPhone 16",
        qty: 1,
        unitPrice: 169000,
        lineTotal: 169000,
      },
      {
        productId: "p19",
        productName: "Cáp USB-C sang Lightning 2m",
        qty: 2,
        unitPrice: 59000,
        lineTotal: 118000,
      },
    ],
    total: 287000,
    actualTotal: 287000,
    paymentMethod: "cash",
    customerId: "c5",
  },
];

export function getStockAlerts(products: Product[]): StockAlert[] {
  return products
    .filter((p) => p.stockQty < p.minStock && p.status === "active")
    .map((p) => ({ product: p, deficit: p.minStock - p.stockQty }))
    .sort((a, b) => a.deficit - b.deficit);
}

export function formatVND(amount: number): string {
  return new Intl.NumberFormat("vi-VN").format(amount) + " ₫";
}

export function formatVNDCompact(amount: number): string {
  if (amount >= 1000000) return (amount / 1000000).toFixed(1) + " triệu ₫";
  return formatVND(amount);
}

export function formatDateVN(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("vi-VN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

export function formatTimeVN(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleTimeString("vi-VN", {
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function formatDateTimeVN(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleString("vi-VN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}
